import = ["/Users/nakano.yoshiyuki/.config/alacritty/dracula.toml"]

[cursor.style]
shape = "Block"

[font]
size = 16

[font.bold]
family = "Monaco"

[font.italic]
family = "Monaco"

[font.normal]
family = "Monaco"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95

[window.dimensions]
columns = 220
lines = 75

[window.padding]
x = 8
y = 4
