# [dein.toml]

[[plugins]]
repo = 'Shougo/dein.vim'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
      \   'colorscheme': 'deus',
      \ }
  set noshowmode
'''

# コメントアウトショートカット 
[[plugins]]
repo = 'tyru/caw.vim'

# ディレクトリ/ファイル操作
[[plugins]]
repo = 'lambdalisue/fern.vim'

# タグ囲み
[[plugins]]
repo = 'alvan/vim-closetag'

# wakatime 用のプラグイン/トラッキング
[[plugins]]
repo = 'wakatime/vim-wakatime'

# coc.nvim (インテリセンス)
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'
